# For local development with hot-reloading for the Flask app
services:
  app:
    build: .
    environment:
      - FLASK_APP=app.server
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0
    volumes:
      - type: bind
        source: ./app
        target: /app/app
